import React from 'react';
import '../styles/globals.css'
import Footer from "../components/Footer";
import Header from "../components/Header";
import Head from "next/head";
import styles from "../styles/Home.module.css";

function MyApp({Component, pageProps}) {
    return (
        <div className={styles.container}>
          <Head>
            <title>Articles</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link
                href="http://db.onlinewebfonts.com/c/415c1cffdc1ffdf955cdd328ad4a4c87?family=Cheltenham"
                rel="stylesheet"
            />
          </Head>

          <Header/>
          <Component {...pageProps} />
          <Footer/>
        </div>

    )
}

export default MyApp
